# Six-university pipeline

Run All here to rebuild stages 02–04 from the frozen raw snapshot. The same pipeline runs headless with `python main.py`.

# Team Pipeline Verification

This notebook is a safe end-to-end verification of the integrated pipeline. It no longer performs a second, separate merge that could overwrite `final.csv` with stale branch outputs.

In [1]:
from pathlib import Path

ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
target = ROOT / "data" / "interim" / "KSU_cleaned.csv"
print("Target:", target)

try:
    target.write_text("x", encoding="utf-8")
    print("notebook write OK")
except OSError as error:
    print("notebook write failed:", type(error).__name__, error)

Target: c:\Users\nawaf\saudi-tech-research\data\interim\KSU_cleaned.csv
notebook write OK

In [2]:
from pathlib import Path
import sys

ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import subprocess
import pandas as pd

# Rebuild from upstream inputs, never concatenate onto an existing final.csv.
# All three notebooks run in separate namespaces, matching independent kernels.
import json
for filename in ["02_profile_clean.ipynb", "03_schema_validate.ipynb", "04_join_transform.ipynb"]:
    path = ROOT / "notebooks" / filename
    notebook = json.loads(path.read_text(encoding="utf-8"))
    from IPython.display import display
    namespace = {"__name__": "__notebook__", "display": display}
    print("Running:", filename)
    for cell_number, cell in enumerate(notebook["cells"], 1):
        if cell["cell_type"] == "code":
            source = "".join(cell["source"])
            exec(compile(source, f"{filename}:cell{cell_number}", "exec"), namespace)

Running: 02_profile_clean.ipynb
  KAUST repository cleaned :    928
  KAUST Crossref cleaned   :    124
  KFUPM Pure cleaned       :    441
  KSU 2025 JSON repairs   :      1
  KSU reviewed enrichment  :      4 records
  KSU cleaned              :  41183
  OpenAlex KAU   cleaned  :   2428
  OpenAlex KKU   cleaned  :   1765
  OpenAlex PSAU  cleaned  :   1691
KAUST cleaned: 1052
KFUPM cleaned: 441
KSU cleaned: 41183
OpenAlex cleaned: 5884

KAUST

              column  missing  missing_percent  required
0        research_id        0             0.00      True
1         university        0             0.00      True
2              title        0             0.00      True
3            authors        1             0.10      True
4   publication_year        0             0.00      True
5   publication_date        6             0.57     False
6           abstract       36             3.42     False
7     research_field     1052           100.00     False
8      tech_category     1052           100.00     False
9            journal      331            31.46     False
10               doi      113            10.74      True
11               url        0             0.00      True
12            source        0             0.00      True

KFUPM

              column  missing  missing_percent  required
0        research_id        0             0.00      True
1         university        0             0.00      True
2              title        0             0.00      True
3            authors        0             0.00      True
4   publication_year        0             0.00      True
5   publication_date      356            80.73     False
6           abstract       20             4.54     False
7     research_field      299            67.80     False
8      tech_category      441           100.00     False
9            journal       26             5.90     False
10               doi       26             5.90      True
11               url        0             0.00      True
12            source        0             0.00      True

KSU

              column  missing  missing_percent  required
0        research_id        0             0.00      True
1         university        0             0.00      True
2              title        0             0.00      True
3            authors        0             0.00      True
4   publication_year        0             0.00      True
5   publication_date    41183           100.00     False
6           abstract    16146            39.21     False
7     research_field    41183           100.00     False
8      tech_category    41183           100.00     False
9            journal        0             0.00     False
10               doi    25561            62.07      True
11               url        0             0.00      True
12            source        0             0.00      True

KAU

              column  missing  missing_percent  required
0        research_id        0             0.00      True
1         university        0             0.00      True
2              title        0             0.00      True
3            authors        0             0.00      True
4   publication_year        0             0.00      True
5   publication_date     2428           100.00     False
6           abstract      395            16.27     False
7     research_field        0             0.00     False
8      tech_category     2428           100.00     False
9            journal      215             8.86     False
10               doi        0             0.00      True
11               url        0             0.00      True
12            source        0             0.00      True

KKU

              column  missing  missing_percent  required
0        research_id        0             0.00      True
1         university        0             0.00      True
2              title        0             0.00      True
3            authors        0             0.00      True
4   publication_year        0             0.00      True
5   publication_date     1765           100.00     False
6           abstract      344            19.49     False
7     research_field        0             0.00     False
8      tech_category     1765           100.00     False
9            journal      125             7.08     False
10               doi        0             0.00      True
11               url        0             0.00      True
12            source        0             0.00      True

PSAU

              column  missing  missing_percent  required
0        research_id        0             0.00      True
1         university        0             0.00      True
2              title        0             0.00      True
3            authors        0             0.00      True
4   publication_year        0             0.00      True
5   publication_date     1691           100.00     False
6           abstract      332            19.63     False
7     research_field        0             0.00     False
8      tech_category     1691           100.00     False
9            journal       83             4.91     False
10               doi        0             0.00      True
11               url        0             0.00      True
12            source        0             0.00      True

KAUST

       columns  duplicate_rows
0  research_id               0
1          doi               0

   publication_year  records
0              2023      928
1              2024       51
2              2025       73

KFUPM

       columns  duplicate_rows
0  research_id               0
1          doi               0

   publication_year  records
0              2023       80
1              2024       87
2              2025      164
3              2026      110

KSU

       columns  duplicate_rows
0  research_id               0
1          doi               8

   publication_year  records
0              2023    12346
1              2024    16134
2              2025    12703

KAU

       columns  duplicate_rows
0  research_id               0
1          doi               0

   publication_year  records
0              2023      725
1              2024      613
2              2025      653
3              2026      437

KKU

       columns  duplicate_rows
0  research_id               0
1          doi               0

   publication_year  records
0              2023      451
1              2024      472
2              2025      551
3              2026      291

PSAU

       columns  duplicate_rows
0  research_id               0
1          doi               0

   publication_year  records
0              2023      495
1              2024      500
2              2025      412
3              2026      284

Running: 03_schema_validate.ipynb
Running: 04_join_transform.ipynb
Joined validated records: 22859
university
KSU      15622
KAU       2428
KKU       1765
PSAU      1691
KAUST      938
KFUPM      415
Name: count, dtype: int64
Technology candidates: 5332
No keyword match: 17527
university
KSU      1483
KAU      1400
KKU      1101
PSAU     1014
KFUPM     211
KAUST     123
Name: count, dtype: int64
Saved final.csv: (5332, 15)
Unique papers (by DOI): 4975
DOIs shared across universities: 320
Task 4 checks passed.

In [3]:
final = pd.read_csv(ROOT / "data/processed/final.csv")
print("Rows:", len(final))
print("Columns:", len(final.columns))
print("Duplicate research_id:", final["research_id"].duplicated().sum())
print("Missing DOI:", final["doi"].isna().sum())
print(final["university"].value_counts())

Rows: 5332
Columns: 15
Duplicate research_id: 0
Missing DOI: 0
university
KSU      1483
KAU      1400
KKU      1101
PSAU     1014
KFUPM     211
KAUST     123
Name: count, dtype: int64

In [4]:
subprocess.run([sys.executable, "-m", "pytest", "-q"], cwd=ROOT, check=True)

CompletedProcess(args=['c:\\Users\\nawaf\\saudi-tech-research\\.venv\\Scripts\\python.exe', '-m', 'pytest', '-q'], returncode=0)

In [5]:
from pathlib import Path
import pandas as pd

ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()

final = pd.read_csv(ROOT / "data" / "processed" / "final.csv")
years = final.groupby("doi")["publication_year"].nunique()
conflicts = years[years > 1].index

print("DOIs with conflicting years:", len(conflicts))
print(
    final[final["doi"].isin(conflicts)][
        ["doi", "university", "publication_year", "title"]
    ].sort_values("doi").to_string()
)

DOIs with conflicting years: 9
                               doi university  publication_year                                                                                                                                                    title
1352  10.1016/j.future.2024.107696        KSU              2025                         Enhancing performance of machine learning tasks on edge-cloud infrastructures: A cross-domain Internet of Things based framework
4592  10.1016/j.future.2024.107696       PSAU              2024                         Enhancing performance of machine learning tasks on edge-cloud infrastructures: A cross-domain Internet of Things based framework
3734     10.1142/s0218348x25400080        KKU              2024                                              AUTOMATING METER CLASSIFICATION OF ARABIC POEMS: A HARRIS HAWKS OPTIMIZATION WITH DEEP LEARNING PERSPECTIVE
1409     10.1142/s0218348x25400080        KSU              2025                                              AUTOMATING METER CLASSIFICATION OF ARABIC POEMS: A HARRIS HAWKS OPTIMIZATION WITH DEEP LEARNING PERSPECTIVE
3905     10.1142/s0218348x25400158        KKU              2024                                    APPLIED LINGUISTICS-DRIVEN ARTIFICIAL INTELLIGENCE APPROACH FOR SENTIMENT ANALYSIS AND CLASSIFICATION ON SOCIAL MEDIA
1237     10.1142/s0218348x25400158        KSU              2025                                    APPLIED LINGUISTICS-DRIVEN ARTIFICIAL INTELLIGENCE APPROACH FOR SENTIMENT ANALYSIS AND CLASSIFICATION ON SOCIAL MEDIA
1413     10.1142/s0218348x25400195        KSU              2025                                          COMPUTATIONAL INSIGHTS INTO ARABIC PROPAGANDA: AN INTEGRATION OF CORPUS LINGUISTICS WITH DEEP LEARNING APPROACH
4102     10.1142/s0218348x25400195        KKU              2024                                          COMPUTATIONAL INSIGHTS INTO ARABIC PROPAGANDA: AN INTEGRATION OF CORPUS LINGUISTICS WITH DEEP LEARNING APPROACH
1550     10.1142/s0218348x25400213        KSU              2025                                     MULTI-CLASS AUTOMATED SPEECH LANGUAGE RECOGNITION USING NATURAL LANGUAGE PROCESSING WITH OPTIMAL DEEP LEARNING MODEL
3925     10.1142/s0218348x25400213        KKU              2024                                     MULTI-CLASS AUTOMATED SPEECH LANGUAGE RECOGNITION USING NATURAL LANGUAGE PROCESSING WITH OPTIMAL DEEP LEARNING MODEL
4104     10.1142/s0218348x25400353        KKU              2024                          ENHANCING CYBERSECURITY VIA ANOMALY RECOGNITION USING THERMAL EXCHANGE FRACTALS OPTIMIZATION WITH DEEP LEARNING ON IOT NETWORKS
1422     10.1142/s0218348x25400353        KSU              2025                          ENHANCING CYBERSECURITY VIA ANOMALY RECOGNITION USING THERMAL EXCHANGE FRACTALS OPTIMIZATION WITH DEEP LEARNING ON IOT NETWORKS
1509     10.1142/s0218348x25400365        KSU              2025  LEVERAGING BLOCKCHAIN WITH CHAOTIC OPPOSITIONAL BARNACLES MATING OPTIMIZER-BASED DEEP LEARNING MODEL FOR SECURE IOT ENVIRONMENT IN CONSUMER ELECTRONICS
4103     10.1142/s0218348x25400365        KKU              2024  LEVERAGING BLOCKCHAIN WITH CHAOTIC OPPOSITIONAL BARNACLES MATING OPTIMIZER-BASED DEEP LEARNING MODEL FOR SECURE IOT ENVIRONMENT IN CONSUMER ELECTRONICS
3768     10.1142/s0218348x25400389        KKU              2024                                           MODELING OF ENHANCED FRACTAL CHEETAH OPTIMIZER WITH DEEP LEARNING FOR INTEGRATED ARABIC DIALECT IDENTIFICATION
1306     10.1142/s0218348x25400389        KSU              2025                                           MODELING OF ENHANCED FRACTAL CHEETAH OPTIMIZER WITH DEEP LEARNING FOR INTEGRATED ARABIC DIALECT IDENTIFICATION
4865     10.1142/s0218348x25400389       PSAU              2024                                           MODELING OF ENHANCED FRACTAL CHEETAH OPTIMIZER WITH DEEP LEARNING FOR INTEGRATED ARABIC DIALECT IDENTIFICATION
1506     10.1142/s0218348x25400468        KSU              2025                                  SECURING INTERNET OF THINGS-ASSISTED CONSUMER ELECTRONICS USING BLOCKCHAIN WITH DEEP LEARNING-BASED USER AUTHENTICATION
4105     10.1142/s0218348x25400468        KKU              2024                                  SECURING INTERNET OF THINGS-ASSISTED CONSUMER ELECTRONICS USING BLOCKCHAIN WITH DEEP LEARNING-BASED USER AUTHENTICATION